root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Lệnh build trỏ đúng vào thư mục chứa file main.go của bạn
  cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
  
  # File thực thi mà Air sẽ chạy sau khi build xong
  bin = "tmp\\main.exe"
  
  # Thêm các file cấu hình vào để khi sửa .env nó cũng tự restart server
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "frontend"]
  delay = 1000
  stop_on_error = true
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = true