ALTER TABLE properties
DROP COLUMN IF EXISTS district,
DROP COLUMN IF EXISTS ward,
DROP COLUMN IF EXISTS latitude,
DROP COLUMN IF EXISTS longitude,
DROP COLUMN IF EXISTS slug,
DROP COLUMN IF EXISTS idempotency_key;
